### ISSUE TITLE
Test mesh width/height alterations not supported (2019.3.14f1)

### ISSUE THREAD

**Issue by HG-Dev** [brookmiles/curved-corner-uvs#1]
Just thought I'd let you know any alteration to the test mesh's width and height fields isn't correctly represented when bending the mesh in 2019.3.14f1.
![image](https://user-images.githubusercontent.com/29112495/82859321-62faea80-9f51-11ea-96b3-03c8d43c8958.png)

**Comment by brookmiles** [comment]
whoops. i didn't actually test the width and height settings ;) thanks for pointing that out
